### ISSUE TITLE
Subtyping: function handling 'long and 'short

### ISSUE THREAD

**Issue by kornelski** [rust-lang/nomicon#126]
> if we need a function that can handle anything that lives for at least 'long, it's perfectly fine for it to be able to handle anything that lives for at least 'short.

That is confusing. The way I understand this sentence is if we have `fn foo(arg: &'long)` that should be able to handle `foo(&'short val)`, which doesn't sound right.

I think it's in the context of "But if we flip it around, …" earlier in the paragraph, so I'm not sure if I'm supposed to flip `'long` and `'short` here.

**Comment by JOE1994** [comment]
I think you're right! It seems that the problematic sentence in the `subtyping` chapter 
has been fixed as below now.

> if we need a function that is supposed to produce something that lives for 'short, it's perfectly fine for it to produce something that lives for 'long.

The new explanation looks good to me now 😃
