### ISSUE TITLE
Update/rewrite "Calling Rust code from C" section

### ISSUE THREAD

**Issue by ghost** [rust-lang/nomicon#138]
This https://doc.rust-lang.org/nomicon/ffi.html#calling-rust-code-from-c
( and even in the book here: https://doc.rust-lang.org/stable/book/ch19-01-unsafe-rust.html#calling-rust-functions-from-other-languages )

has no mention of all the other info needed to accomplish this, such as: compile as a [cdylib](https://speakerdeck.com/dbrgn/calling-rust-from-c-and-java?slide=33) by adding [`crate-type = [ "cdylib" ]`](https://speakerdeck.com/dbrgn/calling-rust-from-c-and-java?slide=54) in `Cargo.toml` `[lib]` section, or using [`cbindgen`](https://github.com/eqrion/cbindgen) to [generate a header file](https://speakerdeck.com/dbrgn/calling-rust-from-c-and-java?slide=55), or the [`gcc` command line](https://speakerdeck.com/dbrgn/calling-rust-from-c-and-java?slide=56) to compile the `.cpp` file.

(**NOTE**: the below link is now invalid as the author deleted their account.)
I've attempted all the needed stuff in a working example [here](https://github.com/howaboutsynergy/reflo/tree/e8b160c223a0dfc84242e830759b0d0ac3ffb573/book/l_19_8_two).

**Comment by Gankro** [comment]
yes this chapter was transplanted from TRPL while I was away, and needs to be completely rewritten.
