### ISSUE TITLE
Rewrite "Implementing Vec" chapter - Unique is permanently unstable 

### ISSUE THREAD

**Issue by tesuji** [rust-lang/nomicon#160]
This chapter use `Unique` to demonstrate how to implement a Vec. But it is
permanently unstable and can only be used by std. Also in
https://github.com/rust-lang/rust/blob/478464570e60523adc6d303577d1782229ca1f93/src/libcore/ptr/unique.rs#L28-L34
it recommends that we should use `NonNull` instead and consider `PhantomData<T>`.

**Comment by eisterman** [comment]
What is the pattern to use instead of Unique? With NonNull?

**Comment by Coder-256** [comment]
I think this is a duplicate of #83.
