### ISSUE TITLE
About "How Safe and Unsafe Interact"

### ISSUE THREAD

**Issue by Tigerly** [rust-lang/nomicon#176]
Hello,

Very good document. I have a question, after reading "How Safe and Unsafe Interact" section, I am still confused about why "Safe Rust inherently has to trust that any Unsafe Rust it touches has been written correctly. On the other hand, Unsafe Rust has to be very careful about trusting Safe Rust."

Would it be possible to explain it a little bit more?

Thanks in advance!

**Comment by JohnTitor** [comment]
Thanks for the report and sorry for the big delay! The paragraphs that follow explain its relationship in more detail. I guess you were confused about the latter sentence ("Unsafe Rust has to be very careful about trusting Safe Rust"), right? It means that Unsafe Rust cannot deal with any inputs from Safe Rust without care, as it may be wrong and can cause UB. Anyway, opened #294 to clarify that, I hope it eases your confusion :)
