### ISSUE TITLE
Alternative Representations: broken link to `representation.md`

### ISSUE THREAD

**Issue by xobs** [rust-lang/nomicon#178]
The page https://doc.rust-lang.org/nomicon/other-reprs.html has a link at the top to a list of all Rust reference types.  This link - https://github.com/rust-lang/unsafe-code-guidelines/tree/master/reference/src/representation.md - is no longer valid.

**Comment by chansuke** [comment]
@xobs Hi. I think the link has been already updated in [this commit](https://github.com/rust-lang/nomicon/commit/4f29478b14cd510ca0c2298ef22917096176f907) :)

**Comment by xobs** [comment]
Thanks, I didn't notice that!
