### ISSUE TITLE
confilct with the conclusion: &mut T is invariant On T

### ISSUE THREAD

**Issue by zylthinking** [rust-lang/nomicon#183]
the code below can be compiled, but it should be rejected because of &mut T is invariant On T;
Is there anything I misunderstand?
```
impl Animal for Cat1 {
    fn snuggle(&self) {
    }

    fn eat(&mut self) {
        println!("cat {}", self.data);
    }
}

impl Cat for Cat1 {
    fn meow(&self) {}
}

fn love(pet: &mut Animal) {
}

fn change() {
    let mut z: Cat1 = Cat1 {
        data: 8
    };
    love(&mut z);
}
```

**Comment by JOE1994** [comment]
I see your point ! Below is a minimal buildable code expanded from your example ([link to playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=27bb7a7f638dea41bbd345a8d4f4bbfb)). Code builds sucessfully with `rustc stable 1.41.0`.
```rust
trait Animal {
    fn snuggle(&self);
    fn eat(&self);
}

struct Cat1 { data: i32 }
impl Animal for Cat1 {
    fn snuggle(&self) {}
    fn eat(&self) { println!("cat {}", self.data); }
}

trait Cat: Animal { fn meow(&self); }
impl Cat for Cat1 { fn meow(&self) {} }

fn love(pet: &mut Animal) { pet.snuggle(); }

fn change() {
    let mut z: Cat1 = Cat1 { data: 8 };
    // Cat1 <: Cat
    // Cat <: Animal
    
    // Since `&mut` has invariance, 
    // `&mut Cat` and `&mut Animal` has no subtype relations
    
    love(&mut z); // Yet works!
}
```
Maybe there is a flaw in the explanation of the `subtyping and variance` chapter, 
or it could be that our understanding of the topic is somehow mistaken..

**Comment by Gankra** [comment]
traits do not engage in subtyping, only lifetimes are used for subtyping. You are demonstrating coercions.

Cat/Dog/Animal is used as an abstraction to provide a simple inheritance relationship for the reader to understand the basic issues before delving into the concrete case of lifetimes.

**Comment by JOE1994** [comment]
> 
> 
> traits do not engage in subtyping, only lifetimes are used for subtyping. You are demonstrating coercions.

If traits don't engage in subtyping, having the highlighted column in the chart (from the chapter `Subtyping and Variance`) seems totally pointless to me.. (please correct me if I'm wrong)
Besides traits, I can't think of other types that allow reasoning of *subtyping* for the `T` column of the table.

![image](https://user-images.githubusercontent.com/10286488/75194687-9e093a00-5726-11ea-8b28-f7f0a88585f4.png)

**Comment by Gankra** [comment]
because T may be something that contains a lifetime like `&'b X`

`&'a mut &'b X` is invariant over `'b` because `&mut T` is invariant over `T`
