### ISSUE TITLE
Broken Link in “Alternative representations”

### ISSUE THREAD

**Issue by Stupremee** [rust-lang/nomicon#189]
In the [Advanced representations](https://doc.rust-lang.org/nomicon/other-reprs.html#alternative-representations) chapter the link to the reference is broken and redirects to a 404 page. 
The link should point [here](https://doc.rust-lang.org/stable/reference/type-layout.html#representations) I guess.

**Comment by JohnTitor** [comment]
Fixed by 4f29478b14cd510ca0c2298ef22917096176f907.
