### ISSUE TITLE
Typo here in exotic-sizes.html

### ISSUE THREAD

**Issue by Teln0** [rust-lang/nomicon#222]
In this paragraph : A trait object represents some type that implements the traits it specifies. The exact original type is erased in favor of runtime reflection with a vtable containing all the information necessary to use the type. The information that completes a trait object pointer is the vtable pointer. The runtime size of the pointee can be dynamically requested from the vtable.

The word "pointee" should be "pointer"

**Comment by ehuss** [comment]
The original looks correct to me.  I read it as "The runtime size of the thing the trait object pointer is pointing to can be dynamically requested from the vtable".  Changing it to "pointer" would mean the size of a pointer, which is always target_pointer_width, and wouldn't really make sense in this context.

**Comment by Teln0** [comment]
Oh ok I read it wrong I think, sorry
