### ISSUE TITLE
Nomicon incorrectly implies that types with alignment > 1 cannot be ZSTs

### ISSUE THREAD

**Issue by joshlf** [rust-lang/nomicon#226]
On the [repr(Rust)](https://doc.rust-lang.org/stable/nomicon/repr-rust.html) page, it reads:

> A type's size must always be a multiple of its alignment. This ensures that an array of that type may always be indexed by offsetting by a multiple of its size.

This wording is ambiguous with respect to zero-sized types. One reading of it (which was my interpretation for years) is that a type's size must be a non-zero multiple of its alignment in order to satisfy the array indexing requirement. In fact, the reality is that the size may be zero regardless of the alignment. It would be good to clarify the wording to make that clear.

cc @jswrenn

**Comment by nico-abram** [comment]
Is zero not a multiple of every number? Either way, clarifying that would be nice since it *does* seem confusing

**Comment by nico-abram** [comment]
I tentatively opened a PR aiming to clarify this https://github.com/rust-lang/nomicon/pull/246
