### ISSUE TITLE
Coercions section: some coercions are missing

### ISSUE THREAD

**Issue by mexus** [rust-lang/nomicon#237]
Currently, the [Coercions](https://doc.rust-lang.org/nomicon/coercions.html) ([src/coercions.md](https://github.com/rust-lang/nomicon/blob/master/src/coercions.md)) section doesn't mention the accepted and implemented (and stabilized) RFC [Allow coercing non-capturing closures to function pointers](https://rust-lang.github.io/rfcs/1558-closure-to-fn-coercion.html).

Could it be that more coercions have been forgotten? :) I can't think of any right now, but I could have also forgotten something xD

## TODO
- [x] RFC 1558 (#238)
- [ ] function items to fn pointers (see below comments)

**Comment by MikailBag** [comment]
Also coercion from unnameable-function-type to fn pointer is not covered.

**Comment by mexus** [comment]
@MikailBag could you provide an example? I don't quite get what exactly the coercion is about..

**Comment by MikailBag** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=aefe8a9bcde0b9ebac8afac2d10be87d

This code shows that `foo` and `bar` have different types

**Comment by mexus** [comment]
Got it! But what about "unnameable function types"?

**Comment by JohnTitor** [comment]
This could go to the reference as per https://github.com/rust-lang/nomicon/issues/230#issuecomment-858248008.
