### ISSUE TITLE
Is the Nomicon still a "draft document"?

### ISSUE THREAD

**Issue by camelid** [rust-lang/nomicon#243]
The README says:

> ## NOTE: This is a draft document, and may contain serious errors
> [...]
> ## Contributing
>
> Given that the Nomicon is still in a draft state, we'd love your help! Please
feel free to open issues about anything, and send in PRs for things you'd like
to fix or change. If your change is large, please open an issue first, so we can
make sure that it's something we'd accept before you go through the work of
getting a PR together.

But this comment is [4 years old](https://github.com/rust-lang/nomicon/commit/3d4b55bdd0e6bc9a4d5dab1e8322053e1048a355). Is it still true that the Nomicon is a draft and may contain serious errors?

**Comment by JohnTitor** [comment]
Since that comment, we've eventually added a lot of sections but now some are outdated. And we still have some TODOs so at least we could say it's "incomplete" (you could also find the issues that need some re-writing, refining, etc.).

**Comment by camelid** [comment]
Although I think a lot of Rust documentation is technically “incomplete”: the Reference and the rustc-dev-guide are the ones I’m thinking of.

**Comment by JohnTitor** [comment]
Though I'm not sure if it's worth removing that message at all.

**Comment by JohnTitor** [comment]
So, I'm going to close this as:

1. Some sections should have "serious errors" e.g. #223.
1. And some other sections should be outdated (see the issue tracker).
1. We don't have enough maintainers to keep the nomicon complete.

Thus, that message isn't _lying_ and I don't think it gives the folks the wrong impression.
If someone wants to remove it, however, feel free to comment here. I'm open to discuss (and even remove) it :)
