### ISSUE TITLE
Is this a typo? The *lifetime* (should be *reference*?) is alive from the place it is created to its last use.

### ISSUE THREAD

**Issue by Celthi** [rust-lang/nomicon#285]
[This line](https://doc.rust-lang.org/nomicon/lifetimes.html#the-area-covered-by-a-lifetime) says

> The **lifetime** (sometimes called a borrow) is alive from the place it is created to its last use.

But at the beginning of the page, it says

> Lifetimes are named regions of code that a reference must be valid for. 

Combining these two sentences, the named region of code is alive from the place it is created to its last use. I don't get the idea of this combined sentence. Is the "**lifetime** is alive" actually "**reference** is alive"?

**Comment by JohnTitor** [comment]
Hmm, that may be confusing, yeah. As you suggested, we could simply replace it with "reference", I think.

**Comment by Celthi** [comment]
If that's the case, I'll raise the PR to rename it.

**Comment by Celthi** [comment]
Fix PR is https://github.com/rust-lang/nomicon/pull/286
