### ISSUE TITLE
Ambiguity w/ Subtyping & Variance Chapter 

### ISSUE THREAD

**Issue by kirawi** [rust-lang/nomicon#305]
[In this chapter](https://doc.rust-lang.org/nomicon/subtyping.html), it uses traits and an inheritance feature to illustrate subtyping, but this can be confusing since readers may associate subtyping with trait bounds/objects. The example is very similar to typical usage of dynamic dispatch, so I suggest changing the example to use `struct`s instead, and explicitly describe the model as inheritance, rather than vaguely describing it as an "extension to the language".

Edit: After seeing how others are finding the same ambiguity, I will flesh out this issue to better review the chapter.
Edit 2: Initial pass done. Most of this section suffers from over-explaining, ambiguous antecedents, contradictions, lack of transitions, convoluted explanations, lack of explanations, re-descriptions of previously described concepts, and much more.

**Comment by SOF3** [comment]
Either way, it is using the deprecated syntax of `Trait` instead of `dyn Trait`, which is confusing to new users.

**Comment by kirawi** [comment]
Maybe the best thing to do is state this is just Rust-like code. That could eliminate a lot of ambiguity too. Though I also agree with your criticism.

**Comment by qsantos** [comment]
The chapter has been fully rewritten by https://github.com/rust-lang/nomicon/pull/340 following the similar remarks in https://github.com/rust-lang/nomicon/issues/339. Are there still standing points in this issue?

**Comment by kirawi** [comment]
No, and I think that additionally watching Jon Gjengset's video on this topic helps a lot. Actually, if any maintainers do read this, I also want to apologize for my tone in the original comment.

**Comment by qsantos** [comment]
Thanks for the prompt answer @kirawi. Is it possible for you to close this issue? It might help make it simpler for other people to navigate the issues.

**Comment by qsantos** [comment]
Thanks @kirawi!
