### ISSUE TITLE
Is section about references still up-to-date

### ISSUE THREAD

**Issue by Ygg01** [rust-lang/nomicon#328]
When looking at https://doc.rust-lang.org/nomicon/references.html

I noticed that the aliasing model is undefined. I'm confused, wasn't Rust implementing [Stacked Borrows as aliasing model](https://plv.mpi-sws.org/rustbelt/stacked-borrows/)?

**Comment by ehuss** [comment]
Unfortunately no. Stacked Borrows is an (excellent) experiment done by Ralf Jung et al. It is possible that a different formulation may emerge in the future based on a different model.  Officially, the exact rules are currently not defined.
