### ISSUE TITLE
wrong comment/docs in "Vec from scratch" chapter?

### ISSUE THREAD

**Issue by lauti7** [rust-lang/nomicon#390]
Hi, I'm opening up this issue because in this [chapter](https://doc.rust-lang.org/nomicon/vec/vec-alloc.html) (Vec from scratch), the code example at the end of the page has one comments which say: 
```rust
 // This can't overflow since self.cap <= isize::MAX.
```
I think the above comment is wrong because `self.cap` is an `usize` type so actually it can be greater than  `isize::MAX`.

Is this actually wrong or am I misunderstanding something? Hope you can help me out.

**Comment by ehuss** [comment]
There is an invariant enforced by an assert just a few lines below that it cannot be over isize::MAX.

**Comment by lauti7** [comment]
Thank you
