### ISSUE TITLE
In Ownership/Lifetimes section, ` 'a: { ` should be a valid syntax

### ISSUE THREAD

**Issue by Multirious** [rust-lang/nomicon#402]
At

> // NOTE: `'a: {` and `&'b x` is not valid syntax!

I believe that this should be a valid syntax with block labeling feature.

**Comment by Multirious** [comment]
This should be an easy fix. I could create a pull request now but just making sure. Please correct me if I'm wrong.

**Comment by ehuss** [comment]
I believe the comment is referring to the fact that it is not valid syntax for referring to a lifetime. We could extend the comment to say that ("…is not valid syntax. They are used here to illustrate the lifetime regions.") or something like that.

**Comment by JohnTitor** [comment]
Closing as wontfix, I assume @Multirious read the above as they added a reaction. Thank you for reporting anyway!
