### ISSUE TITLE
`Exception Safety` section: `Hole::get` probably doesn't have to be `unsafe`

### ISSUE THREAD

**Issue by frozenspider** [rust-lang/nomicon#426]
https://doc.rust-lang.org/nomicon/exception-safety.html

```rust
struct Hole<'a, T: 'a> {
    data: &'a mut [T],
    /// `elt` is always `Some` from new until drop.
    elt: Option<T>,
    pos: usize,
}

impl<'a, T> Hole<'a, T> {
    // ...

    unsafe fn get(&self, index: usize) -> &T { &self.data[index] }

    // ...
}
```

Why is `get` here marked as `unsafe`? It doesn't seem to be performing anything particularly unsafe, any more so than regular safe code might do. Rust compiler also doesn't require it to be `unsafe`.

**Comment by JohnTitor** [comment]
I guess it just missed on writing, a PR is welcome!
