### ISSUE TITLE
Imprecision in "What Unsafe Rust Can Do"

### ISSUE THREAD

**Issue by alimf17** [rust-lang/nomicon#437]
In "[What Unsafe Can Do](https://doc.rust-lang.org/nomicon/what-unsafe-does.html)", the fourth bullet point on the first list is "Mutate statics." What it should say is "Access or modify mutable statics", same as "Rust By Example"'s list: the compiler does not allow you to read a mutable static without an unsafe block.

**Comment by ehuss** [comment]
Closed by #457.
