### ISSUE TITLE
Which one does the last code in 8.1. Races cause, a data race or a race condition?

### ISSUE THREAD

**Issue by shinmili** [rust-lang/nomicon#466]
The comment in the last code in [8.1. Races](https://doc.rust-lang.org/nomicon/races.html) says "This is a race condition", but the description right above says "We can cause a data race". Which one is correct?

I guess it doesn't cause a data race, because all of the accesses to the `AtomicUsize` are synchronized, so the third requirement of a data race "one or more of them is unsynchronized" is not met.

**Comment by Enselic** [comment]
Yeah that seems like a typo. Fixed by https://github.com/rust-lang/nomicon/pull/470.
