### ISSUE TITLE
repr(Rust) page doesn't reflect the latest data layout optimizations

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/nomicon#51]
The page about repr(Rust) says that we don't have much in the way of data layout optimization "as of rust 1.0", but as of 
PR [45225](https://github.com/rust-lang/rust/pull/45225) we got a lot more going on in the optimization department.

**Comment by Gankro** [comment]
yep, would be nice to explain some of these things.

**Comment by JohnTitor** [comment]
The note has been removed by #43.
