### ISSUE TITLE
Unclear use of "metaphor" in Subtyping and Variance

### ISSUE THREAD

**Issue by varkor** [rust-lang/nomicon#54]
[In the section on **Subtyping and Variance**](https://doc.rust-lang.org/nomicon/subtyping.html#variance), some important variances include:
> - `&'a T` is variant over `'a` and `T` (as is `*const T` by metaphor)
> - [...]
> - `UnsafeCell<T>`, `Cell<T>`, `RefCell<T>`, `Mutex<T>` and all other interior mutability types are invariant over `T` (as is `*mut T` by metaphor)

It's unclear (to me) what the phrase "by metaphor" means here. Perhaps this could be rephrased to make it a little clearer?

**Comment by Gankro** [comment]
Ah yeah that's not great. Good point!

**Comment by JOE1994** [comment]
This issue has been resolved in PR #102 and should be safe to be closed now 😃
